#!/bin/bash

if [ $# -eq 0 ]
then
  selected=$(ls -p | fzf --bind "ctrl-a:select-all" --bind "ctrl-d:deselect-all" -m)
  if [ -z "$selected" ]
  then
    exit 1
  fi
  
  mkdir -p ~/.grab
  file=~/.grab/selected

  out=""
  IFS=' ' read -ra items <<< $(echo $selected)

  for item in ${items[@]}
  do
    out="$out $PWD/$item"
  done

  # trim last space with xargs
  echo $(echo $out | xargs) > $file
fi

dir=.

if [ $# -gt 1 ]
then
  dir=$2
fi

if [ $# -gt 0 ]
then
  file="$HOME/.grab/selected"
  IFS=' ' read -ra items <<< $(cat $file)

  if [ $1 == "cut" ]
  then
    for item in ${items[@]} 
    do
      mv $item $dir 
    done
  elif [ $1 == "copy" ]
  then
    for item in ${items[@]} 
    do
      if [[ $item == */ ]]
      then
        cp -r $item $dir 
      else
        cp $item $dir
      fi
    done
  else
    echo "unknown command $1"
    exit 1
  fi
fi

exit 0
